const { SlashCommandBuilder } = require(`discord.js`);
module.exports = {
    data:   new SlashCommandBuilder()
        .setName('cbt')
        .setDescription('cock and ball torture'),
    async execute(interaction, Discord, message, Lyuca, sdPrefix, fs, DatabaseArr, msgArr, cmdArr){
        let base = (interaction) ? interaction : message;
        cbt = `Cock and Ball Torture from Wikipedia the free encyclopedia at \`https://en.wikipedia.org/wiki/Cock_and_ball_torture\`\nCock and ball torture (cbt) is a sexual activity involving torture of the male genitals. This may involve directly painful activity such as wax play, genital spanking, squeezing, ball busting, genital flogging, ureteral play, tickle torture, erotic electrostimulation, or even kicking. The recipient of such activities may receive direct physical pleasure via masochism from knowledge that the play is pleasing to a sadistic dominant.\n\nContents:\n1) In pornography\n2) Ball stretcher\n3) Parachute\n4) Humbler\n5) Testicle cuff\n\nSection 1, in pornography:\nIn addition to its occasional role in BDSM pornography, Tamakeri literally ball kicking, is a separate genre in Japan. One notable actress in Tamakeri is Erika Nagai, who typically uses her martial arts skills to knee or kick men in the testicles.\n\nSection 2, ball stretcher:\nA ball stretcher is a sex toy that is fastened around a man in order to elongate the scrotum and provide a feeling of weight pulling the testicles away from the body. While leather stretchers are most common, other models are made of steel rings that are fastened with screws, causing additional mildly uncomfortable weight to the wearer.  The length of the stretcher may vary from 1-4 inches, and the steel models can way as much as 5 pounds.`
        cbt2 = `Section 3, Parachute:\nA parachute is a small collar, usually made from leather which fastens around the scrotum, and weights can be hung. Conical in shape, with three or four short chains hanging beneath, to which weights can be attached. Used as part of cock and ball torture within a BDSM relationship, the parachute provides a constant drag, and squeezing effect on the man's testicles, moderate weights of 3-5 kg can be suspended, especially during bondage. Smaller weights can be used when the man is free to move, when the swinging effect of the weight can restrict sudden movements, as well as providing a visual stimulus for the dominant partner.\n\nSection 4, Humbler:\nA humbler is a BSDM physical restraint device used to restrict movement of a submissive male participant (maple) in a BDSM scene. The humbler consists of a testicle cuff device that clamps around the base of the scrotum, mounted in the center of a bar that passes behind the thighs and at the base of the buttocks. This forces the wearer to keep his legs forward, as any attempt to straighten the legs even slightly pulls directly on the scrotum, causing from considerable discomfort to extreme pain.\n\nSection 5, Testicle cuff:\nA testicle cuff is a ring-shaped device around the scrotum between the body and the testicles.`
        base.reply(cbt);
        base.channel.send(cbt2);
    }
}